### ISSUE TITLE
FreeBSD build broken

### ISSUE THREAD

**Issue by Crapworks** [authelia/authelia#1827]
Hi Folks,

the [FreeBSD port](https://svnweb.freebsd.org/ports/head/www/authelia/) for Authelia seems to be broken for a while now (see also [this redit post](https://www.reddit.com/r/freebsd/comments/j20vb5/has_anyone_gotten_authelia_port_to_work_all_i_get/))

I tried to get it working on my own FreeBSD installation and had the same problem: Whatever I did, I just got a white page instead of the Authelia login. After digging around a bit, I realized that it was showing the default empty index.html [from here](https://github.com/authelia/authelia/blob/master/internal/server/public_html/index.html). Going through some commits, it looks like you switched to assets integrated into the binary and removed the option to specify the asset location via `PUBLIC_DIR` environment variable (#938). You docker build is moving the actual content to the location in `interal/server` while the FreeBSD port does not, so it ends up with no public_html files and no option to point to them externally (as far as I am aware, am I missing something here?)

I got it working by manually putting the files there but I neither know the ports build system enough to know how to properly fix this upstream, and I am not a fan of compiling new versions like this myself. So it would be great if you could take a look at this and fix it in the ports Makefile.

Thanks!

**Comment by james-d-elliott** [comment]
Ah interesting. Thanks for reporting. We shall look into it!

**Comment by james-d-elliott** [comment]
@Crapworks allegedly the latest build should be working according to the maintainer of the package (we don't package it for BSD ourselves).

**Comment by james-d-elliott** [comment]
@Crapworks did you manage to get it working? If so I'd like to close this issue. If not I'd like to let the packager know.

**Comment by Crapworks** [comment]
Hey @james-d-elliott 

sorry for the late reply but I wanted to test it properly.

So I created a fresh jail with `12.2-RELEASE` and got the current ports with `portsnap fetch && portsnap extract` and build authelia with `cd /usr/port/www/authelia && make install clean`.

Again, the public_html folder just contained the empty index.html:

```
curl -D - localhost:9091
HTTP/1.1 200 OK
Date: Thu, 18 Mar 2021 15:01:07 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Content-Security-Policy: default-src 'self' ; object-src 'none'; style-src 'self' 'nonce-m707jep42WS6Ko6FOA8C1B3kVtS7Hr8Q'

```

So from what I can see, this is still broken for FreeBSD (also looking at the Makefile, the only thing that changed is the version bump, so I really doubt that the latest build changed anything besides that).

Let me know if you need more information.

**Comment by james-d-elliott** [comment]
This has been fixed upstream @Crapworks and confirmed by another user. Thus I'm closing it for now. If you have no success with the latest package please feel free to comment and reopen this issue.
