### ISSUE TITLE
Support for OpenID Connect 1.0 (Provider)

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#189]

**Comment by Beanow** [comment]
Likewise, http://openid.net/connect/

**Comment by clems4ever** [comment]
Hello @Beanow , thank you for your interest. OpenID is indeed a protocol that would be cool to see in Authelia at some point.

**Comment by khimaros** [comment]
I would love to see this as well.

Possible route: Authelia as a coreos/dex frontend.

**Comment by jpds** [comment]
This would be particularly useful as oauth2_proxy appears to have been abandoned: https://github.com/bitly/oauth2_proxy/issues/628

**Comment by xeor** [comment]
Any updates on this?

**Comment by clems4ever** [comment]
Not started.

**Comment by khimaros** [comment]
Would IndieAuth be easier to support?

**Comment by clems4ever** [comment]
Hello @khimaros , the problem is not really technical but that nobody has implemented it so far instead and I'm very busy lately.
To improve the situation I'm simplifying the dev workflow in order for people to be more confident in contributing to Authelia. That way I hope we will implement great features faster (like OAuth, push notifications, SMS auth, access logs, etc...)
I don't know about IndieAuth but again, the issue is not technical.

**Comment by clems4ever** [comment]
FYI, this issue is being worked on actively. I'm doing a POC using fosite and I will come up with a design proposal in the next few days (today?) before moving forward.

**Comment by lukasmrtvy** [comment]
@clems4ever  are You aware of https://github.com/dexidp/dex ?

**Comment by clems4ever** [comment]
Hello @lukasmrtvy , yes, I'm aware this one exists. I don't have any experience with those so I chose fosite because I quickly found a complete and simple example that I was able to easily integrate to Authelia but I'm completely open to discuss about dex.
Do you have any experience with dex? Any argument in favor of dex vs fosite?

**Comment by clems4ever** [comment]
### Design proposal

Implementation of OIDC is a complex task so we'd rather split the development into several phases. Here is the design of the first
phase as I see it.

#### New endpoints
- /.well-known/openid-configuration --- to support the discovery RFC (https://openid.net/specs/openid-connect-discovery-1_0.html) required by https://github.com/coreos/go-oidc.
- /api/oidc/auth --- authorize endpoint for OAuth2/OIDC generating the authorization code grant.
- /api/oidc/jwks --- Exposing the JWK Set containing the public keys for backends to verify Bearer tokens (key rotation not yet supported in phase 1).
- /api/oidc/token --- token endpoint for OAuth2/OIDC. We retrieve the token, refresh_token and id_token from this endpoint given the authorization code.

#### Workflow
1. The user visit app.example.com (oidc enabled) and gets redirected to login.example.com/api/openid/auth.
   If user is not authenticated, go to 3., if she is go to 4.
3. The user is redirected to login.example.com/ to authenticate according to ACLs. All parameters of the OIDC requests are stored in the user session.
4. If the user has not consented yet, go to 5, otherwise go to 7.
5. she is redirected to login.example.com/consent where she is presented with the consent screen to review the scopes and accept or deny. If the user accepts go to 6. otherwise go to 7.
6. The consent is stored in db, in a newly created table described below.
7. The user gets redirected to the redirection url provided initially.

#### Database
A new table is needed to store user consents.
`CREATE TABLE oauth_consents (username VARCHAR(100) PRIMARY KEY, client_id VARCHAR(256), scopes TEXT);`
The consents are stored in order to skip the consent screen once accepted. This could be revoked once we have an interface for users.

#### Configuration
The configuration of OpenID Connect is done in the yaml file (and will be migrated to database when the configuration is moved).

Here is an example of the Yaml configuration:

```
openid:
  # The secret used to sign the id tokens (jwt)
  openid_issuer_private_key: lzjemfjka (in PAM format)
  # The secret used to sign the access and refresh tokens (https://dzone.com/articles/how-to-improve-oauth-security-with-hmac-validation).
  oauth2_hmac_secret_key: azmljefzjml

  # The configuration of allowed clients
  clients:
    - client_id: myapp
      client_secret: this_is_a_secret
      redirect-uris:
        - http://localhost:8080/oauth2/callback
        - http://myapp.example.com/oauth2/callback
```

#### ID Token claims
- Issuer is set to the protected domain as stored in the "session" section.
- Subject is set to the username of the user.
- Email claim is added to the token.
- Expiration is set to the same expiration as the user session.

#### SDK
Two sdks have been reviewed: dex and fosite. Fosite is currently being tested. There is no hard commitment and we are
open to feedbacks on that matter.

_________________________________________________

### Phase 2+ (ideas)

Support key rotation in later stages.
Support token revocation.

**Comment by clems4ever** [comment]
@james-d-elliott , @nightah , let me know what you think.

**Comment by nightah** [comment]
Great write up, my only concern really is around around token revocation day 1.

If we're expecting Phase 2 to be followed quite quickly then that concern is partially allayed.

Perhaps the interim step between Phase 1 -> Phase 2 could be to include documentation on how to manually remove constents (simple SQL statement(s)) along with the Phase 1 documentation, what do you think?

**Comment by clems4ever** [comment]
I'm ok to handle revocation in phase 1 but we need to be aware that there are 2 kinds of revocation:
1. revocation of consent as you suggest.
2. revocation of session (the id token, the access token and the refresh token).

The problem is that the revocation of consent would require a dedicated interface as the one we intend to introduce for users and/or admins. For the revocation of session, it's the same problem as the revocation of cookie, the proper way would be to provide the interface for admins to do it.

I think your suggestion of documenting the way to do it manually is sound for the time being. We'll improve with the new interfaces.

**Comment by james-d-elliott** [comment]
I can't see any issues, seems like a good proposal.

**Comment by Ornias1993** [comment]
One for Phase 3:
Single Log out (after revocation is implemented)

OpenID Connect includes a way of doing so in the standard. WSO2 has a very nice breakdown of the two OpenID Connect options (front channel and back channel):
https://docs.wso2.com/display/IS580/OpenID+Connect+Single+Logout

(although a LOT of systems don't implement this very well, such as Nextcloud, if that ever implements anything correctly tbh)

**Comment by adyanth** [comment]
@clems4ever any plans of implementation for SAML along with OIDC for OAuth2? Or will it be just OIDC?

**Comment by Ornias1993** [comment]
@adyanth How about one thing at a time ;)

**Comment by lukas-hetzenecker** [comment]
@adyanth for SAML see #493

**Comment by Ornias1993** [comment]
@clems4ever It looks like you are not actively working on this anymore?
https://github.com/authelia/authelia/tree/oidc

**Comment by Ornias1993** [comment]
Okey... @nightah @james-d-elliott Do I understand correctly from this that @clems4ever is currently unavailable/inactive?

If so, Can one of you post a TLDR what parts of OIDC support in the OIDC branch still needs work, in case others want to jump in and assist?

**Comment by nightah** [comment]
@Ornias1993 yes I believe that is the case.

I personally haven't tested the branch but last I recall @clems4ever was working on the frontend elements to finalise the PR.

I'm a little time poor at the moment, though I'll see if I can get the opportunity over the next couple of week to run it up and see if I can test it myself to see where it is at.

**Comment by tomlawesome** [comment]
Any more progress here at all? Is it still an active priority? (I see it's on the road map).

**Comment by Ornias1993** [comment]
@tomlawesome Did you try to click the first link above your post and actually look at it?! >.<

**Comment by tomlawesome** [comment]
Awesome, thanks. Sorry I’m very new to GitHub. Will try and look for things better 😊

**Comment by clems4ever** [comment]
It's fine :).
A little update here because I know a lot of users are waiting for this one and are probably as excited as we are about it. So we have a decent first shot of OIDC implementation for which we fix the last remaining things and also add more tests to ensure great level of quality (and obviously security). This version is planned to be released in beta hopefully in the next couple of days. It will be a way for us to get feedback on the way until it is feature complete and declared GA.

I know this is an old one but stay tuned! It will be worth it.

**Comment by james-d-elliott** [comment]
Here's a little taste of the consent screen. :)

![image](https://user-images.githubusercontent.com/3903683/114780710-1a435e80-9dbb-11eb-9ece-5c272f5c1597.png)

**Comment by clems4ever** [comment]
We are happy to announce that we have just merged the first big part of OpenID Connect into Authelia. Please note that it's still in beta, the time for us to add production critical features like token revocation and storing information in a safer place than memory in order for sessions to survive a restart and for OIDC to work in HA environments.
However, it's available and you can already try it out for yourself and give us feedback while waiting general availability.

I want to say a big thank you to you @james-d-elliott and @nightah, core team members, for your enormous contribution to this PR, in code, reviews, design discussions, research and everything else. It's been an amazing team work and I'm very happy to work with you on this amazing project. Now let's go to GA!

Next steps are:
1. Implement and document a use case leveraging a well known app (most likely Grafana).
2. Improve documentation if needed.
3. Keep improving code coverage.
3. Implement a prod ready storage layer in order for OIDC sessions to survive Authelia restarts and for sessions to work in HA environments.
4. Implement token revocation.

**Comment by fredericrous** [comment]
So happy to hear these great news, good job to the core team!
For the following, `Implement and document a use case leveraging a well known app`, could you please consider  documenting `Nextcloud` integration as this is the most common app used by ppl who selfhost their own little cloud

**Comment by lukas-hetzenecker** [comment]
Thanks for the release, you rock! :partying_face: 

I tried to test it with Gitlab (sameersbn/docker-gitlab), but unfortunately it was not successful yet.
The used configuration was:

gitlab env:
```
    - OAUTH2_GENERIC_NAME=Auth
    - OAUTH2_GENERIC_APP_ID=gitlab
    - OAUTH2_GENERIC_APP_SECRET=******
    - OAUTH2_GENERIC_CLIENT_SITE=https://auth.****.com
    - OAUTH2_GENERIC_CLIENT_TOKEN_URL=/api/oidc/token
    - OAUTH2_GENERIC_CLIENT_AUTHORIZE_URL=/api/oidc/authorize
```

authelia conf:
```
identity_providers:
  oidc:
    hmac_secret: *****
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
***
      -----END RSA PRIVATE KEY-----
    clients:
      - id: gitlab
        description: gitlab
        secret: ****
        authorization_policy: one_factor
        redirect_uris:
          - https://git.***.com/users/auth/oauth2_generic/callback
        scopes:
          - openid
          - groups
          - email
          - profile
```

Gitlab shows the OAUTH2 "Sign in" link, but when clicking on it the HTTP redirect seems to be empty and the page only displays "Redirecting to ...":
```
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 302 
[...]
< location: 
< server: nginx
[...]
Redirecting to ...
```

I think this is because [Authelia does not yet implement UserInfo](https://github.com/authelia/authelia/blob/e7f25b7e3d942391e48ccc0ecabcb2cf8feba3a2/internal/handlers/register_oidc.go) (`omniauth_providers` / `args` / `client_options` / `user_info_url` - see https://gitlab.com/satorix/omniauth-oauth2-generic or `OAUTH2_GENERIC_CLIENT_USER_INFO_URL`), which seems to be required.

I will definitely test it again when the still missing endpoints are implemented as well. 
In the meantime, I will implement it for Grafana :)

**Comment by james-d-elliott** [comment]
@lukas-hetzenecker 

> 
> 
> Good job team! I just tested it on Grafana, would you be interested in some draft for documentation mentioned above?

We'd definitely be interested in someone making a doc! Our docs are all in markdown so should be relatively easy to contribute.

**Comment by neunzehn86** [comment]
First of all, thanks for the great work. I'm excited to see what else will come.

I'm read through many docs and comments so please apologize me if i expect something to work but it's not yet implemented.

> Gitlab shows the OAUTH2 "Sign in" link, but when clicking on it the HTTP redirect seems to be empty and the page only displays "Redirecting to ...":

> I think this is because [Authelia does not yet implement UserInfo](https://github.com/authelia/authelia/blob/e7f25b7e3d942391e48ccc0ecabcb2cf8feba3a2/internal/handlers/register_oidc.go) (`omniauth_providers` / `args` / `client_options` / `user_info_url` - see https://gitlab.com/satorix/omniauth-oauth2-generic or `OAUTH2_GENERIC_CLIENT_USER_INFO_URL`), which seems to be required.

Not exactly. I made it a little further.
The redirect URL in Authelia config should be for your GitLab configuration: `https://git.***.com/users/auth/Auth/callback`

Here is my example:

GitLab config:
```
gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_allow_single_sign_on'] = ['auth']
gitlab_rails['omniauth_block_auto_created_users'] = false
gitlab_rails['omniauth_providers'] = [
  {
    "name" => "oauth2_generic",
    "app_id" => "gitlab",
    "app_secret" => "***",
    "args" => {
      "name": "auth",
      "strategy_class": "OmniAuth::Strategies::OAuth2Generic",
      "access_type" => "offline",
      "approval_prompt" => "",
      "client_options": {
        "site": "https://auth.***",
        "authorize_url": '/api/oidc/authorize',
        "token_url": '/api/oidc/token'
        #,
        #"user_info_url": ""
      }
    }
  }
]
```

Authelia config:
```
identity_providers:
  oidc:
    hmac_secret: ***
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      ***
      -----END RSA PRIVATE KEY-----
    clients:
      - id: gitlab
        description: GitLab
        secret: ***
        authorization_policy: one_factor
        redirect_uris:
          - https://git.***/users/auth/auth/callback
        scopes:
          - openid
          - groups
          - email
          - profile
        grant_types:
          - refresh_token
          - authorization_code
```

I took this example (Nextcloud & Gitlab; https://www.claudiuscoenen.de/2018/10/oauth2-with-nextcloud-provider-and-gitlab-client/) which worked with latest Nextcloud (21) and Gitlab-CE (gitlab/gitlab-ce:13.11.3-ce.0).

I just tried with Nextcloud to be sure that all works as expected. Now with Authelia it doesn't work.

When i click on the Button on GitLab-Loginpage for external authentication i see the Authelia Sign In page. After i enter my credentials i'm back on the GitLab-Loginpage and there comes the following Message: `Could not authenticate you from Auth because "404 page not found ".`

The problem here i think is, that the `https://auth.***/api/oidc/token` not working. I only see my 404 error page.

If i already logged in with Authelia and then click on the GitLab-Loginpage Button for external authentication, it forwarded me to the consent page, but it's blank. There is an error `Cannot read property 'map' of null at ConsentView.tsx:88`

On the consent page the API request to `https://auth.***/api/oidc/consent` responds the following 
```JSON
{
   "status":"OK",
   "data":{
      "client_id":"gitlab",
      "client_description":"GitLab",
      "scopes":null,
      "audience":null
   }
}
```

**Comment by hrenard** [comment]
Hi, it's a very exciting feature !
I tried it with HedgeDoc, but I've also encountered an issue with the [UserInfo](https://openid.net/specs/openid-connect-basic-1_0.html#UserInfo) endpoint which seems unfortunately to be required.
Do you plan on adding it ?
Thanks for your work !

**Comment by lukas-hetzenecker** [comment]
Thanks for the amazing fast response. Already found the new image, and gave it a try.
I can feel we are getting closer now.

With the [above](https://github.com/authelia/authelia/issues/189#issuecomment-836603320) mentioned gitlab config, and the following authelia config:

```
identity_providers:
  oidc:
    hmac_secret: ****
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      *****
      -----END RSA PRIVATE KEY-----
    clients:
      - id: gitlab
        description: git.hetzenecker.me
        secret: ****
        authorization_policy: one_factor
        redirect_uris:
          - https://git.***.com/users/auth/openid_connect/callback
        scopes:
          - openid
          - groups
          - email
          - profile
```

I am able to click the openid "Auth" button in Gitlab, get directed to the Authelia Consent Screen, can Click "Accept", get to the gitlab redirect URL..

.. and then a 500 error code from Gitlab :-( 

The Gitlab error log shows only a cryptic runtime error message:

```
*** /var/log/gitlab/production.log ***
Started POST "/users/auth/openid_connect?remember_me=1" for 10.32.0.1 at 2021-05-10 21:48:17 +0000
Processing by Gitlab::RequestForgeryProtection::Controller#index as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "remember_me"=>"1"}
Completed 200 OK in 0ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 106)
Started GET "/users/auth/openid_connect/callback?code=[FILTERED]&scope=openid&state=6725f7a24d040522548034c548c9ff04" for 10.32.0.1 at 2021-05-10 21:48:19 +0000
  
RuntimeError (No Host Info):
  
lib/gitlab/request_profiler/middleware.rb:17:in `call'
lib/gitlab/jira/middleware.rb:19:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:21:in `call'
lib/gitlab/middleware/multipart.rb:172:in `call'
lib/gitlab/middleware/read_only/controller.rb:50:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:21:in `call'
config/initializers/fix_local_cache_middleware.rb:11:in `call'
lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:21:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:76:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'
Started GET "/-/readiness" for 10.44.0.0 at 2021-05-10 21:48:25 +0000
Processing by HealthController#readiness as */*
Completed 200 OK in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 245)
*** /var/log/gitlab/production_json.log ***
```

This has me puzzled, the URL looks correct, so not really sure what is going wrong here.
A internet search shows this could be a wrong issuer field in the openid-configuration (doesn't seem to be the case here), and lots and lots of similar unanswered forum posts.

How I'll be eventually able to provide an adequate answer here :)

**Comment by james-d-elliott** [comment]
Interesting, I wonder why. I might make a patch to just the intended fix, I did change the JWKs in that PR but everything looked fine in testing.

**Comment by james-d-elliott** [comment]
@lukas-hetzenecker If you feel like it and have time, can you try this? Otherwise I can look at setting up GitLab tonight.


    docker pull authelia/authelia:fix-missing-oidc-well-known-meta
    docker pull ghcr.io/authelia/authelia:fix-missing-oidc-well-known-meta

**Comment by lukas-hetzenecker** [comment]
@james-d-elliott i'm running now ghcr.io/authelia/authelia:fix-missing-oidc-well-known-meta@sha256:a64f2a8bb76cd24b3770e121a30bc5e0f712bc1e1c2bbd68a0e8aa14207ce2e2

Unfortunately same error with the same stacktrace (by the way, also with the previous build - gitlab seems to ignore the values in subject_types_supported).

The only difference between fix-missing-oidc-well-known-meta and refactor-oidc I saw in api/oidc/jwks was the kid, all other values stayed the same.

```
+ "kid": "main-key",
- "kid": "64f75d8fd5462732964391c5e51fd17856d932c9631221d64a70456e78750b77",
```

Will go to bed now, and play around with it tomorrow again ;)

**Comment by georglauterbach** [comment]
Hey guys,

I'm tuning in as I want to use Authelia as an OIDC provider for GitLab too. I've been using Authelia over the last couple of months with Traefik (very) successfully - thank you guys for the great work!

So I figured I'd give Authelia's OIDC beta a shot with my self-hosted GitLab instance. Before deploying it though, I'd like to point out some difficulties I had thus far and ask a question or two:

1. I've been using the [Authelia documentation about OIDC](https://www.authelia.com/docs/configuration/identity-providers/oidc.html) and could not figure out what the `issuer_private_key` is. The description "The private key in DER base64 encoded PEM format used to encrypt the OpenID Connect JWT’s." does not help really. For those familiar with OIDC, it may be obvious, but people like me that just want to get it to work without understanding the very details, the docs could be improved :) _So what's this key about?_
2. I've been looking at this issue's history and tried to come up with a configuration for Authelia and GitLab:

This is the GitLab OmniBus configuration file (in Ruby)

``` Ruby
# GitLab OmniBus Config
# https://docs.gitlab.com/ee/administration/auth/oidc.html

gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_allow_single_sign_on'] = ['auth']
gitlab_rails['omniauth_block_auto_created_users'] = false
gitlab_rails['omniauth_providers'] = [
  { 'name' => 'openid_connect',
    'label' => 'Authelia OpenID',
    'args' => {
      'name' => 'openid_connect',
      'scope' => [
        'openid',
        'groups',
        'email',
        'profile'
      ],
      'response_type' => 'code',
      'issuer' => 'https://auth.itbsd.com',
      'discovery' => true,
      'client_auth_method' => 'query',
      'send_scope_to_token_endpoint' => true,
      'client_options' => {
        'identifier' => 'gitlab',
        'secret' => '${OIDC_CLIENT_SECRET}',
        'redirect_uri' => 'https://gitlab.example.com/users/auth/openid_connect/callback'
      }
    }
  }
]
```

and this the Authelia configuration (in YAML, thank god)

``` YAML
# Authelia OIDC configuration
# https://www.authelia.com/docs/configuration/identity-providers/oidc.html

identity_providers:
  oidc:
    hmac_secret: ${HMAC_SECRET}            # <-- self-genrated (?)
    issuer_private_key: |                  # <-- what actually is this?
      -----BEGIN RSA PRIVATE KEY-----
      ***
      -----END RSA PRIVATE KEY-----
    clients:
      - id: gitlab
        description: GitLab
        secret: ${OIDC_CLIENT_SECRET}      # <-- self-genrated (?)
        authorization_policy: one_factor
        redirect_uris:
          - https://gitlab.example.com/users/auth/openid_connect/callback
        scopes:
          - openid
          - groups
          - email
          - profile
```

_Does this look reasonable?_

I would have already tried it, but without the answer to 1), there is no point. I will report back the results when I'm able to deploy it, that is when 1) is answered.

**Comment by nightah** [comment]
> 1. I've been using the [Authelia documentation about OIDC](https://www.authelia.com/docs/configuration/identity-providers/oidc.html) and could not figure out what the `issuer_private_key` is. The description "The private key in DER base64 encoded PEM format used to encrypt the OpenID Connect JWT’s." does not help really. For those familiar with OIDC, it may be obvious, but people like me that just want to get it to work without understanding the very details, the docs could be improved :) _So what's this key about?_

@georglauterbach it's the private key from a RSA key pair, you can generate a key pair with `authelia rsa generate` it will write out a `key.pem` and `key.pub` into your current directory.

> ```yaml
> # Authelia OIDC configuration
> # https://www.authelia.com/docs/configuration/identity-providers/oidc.html
> 
> identity_providers:
>   oidc:
>     hmac_secret: ${HMAC_SECRET}            # <-- self-genrated (?)
>     issuer_private_key: |                  # <-- what actually is this?
>       -----BEGIN RSA PRIVATE KEY-----
>       ***
>       -----END RSA PRIVATE KEY-----
>     clients:
>       - id: gitlab
>         description: GitLab
>         secret: ${OIDC_CLIENT_SECRET}      # <-- self-genrated (?)
>         authorization_policy: one_factor
>         redirect_uris:
>           - https://gitlab.example.com/users/auth/openid_connect/callback
>         scopes:
>           - openid
>           - groups
>           - email
>           - profile
> ```

Yes the `hmac_secret` and `secret` can be self generated.
We recommend a 32+ character, random generated string.

> 3. What are the environment variables' names for the secrets mentioned above (`hmac_secret` and `issuer_private_key`) to use a file (mounted by a container engine like Docker as a secret)? For example, the session secret can be provided via the `AUTHELIA_SESSION_SECRET_FILE` environment variable. Deploying them in Kubernetes, is there a better solution?

The environment variables for all secrets are defined in our [docs](https://www.authelia.com/docs/configuration/secrets.html#environment-variables).

In your case you're looking for:
* `AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE`
* `AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE`

As to whether there's a better way to deploy these in K8s I'll let @james-d-elliott respond because he's much more knowledgeable in that area.

> 4. In the Authelia configuration, `identity_providers::oidc::clients::secret` is stored in plain text. Will this change?

It's very likely.

**Comment by georglauterbach** [comment]
@nightah Thank's for your response :)

I still got one more question:

>  it's the private key from a RSA key pair

What is this RSA key for, who has the public key (does the public key even matter)? I currently do not understand what is being done with this key, therefore I am wondering why one would just need the private part :)

**Comment by james-d-elliott** [comment]
> 
> 
> @nightah Thank's for your response :)
> 
> I still got one more question:
> 
> > it's the private key from a RSA key pair
> 
> What is this RSA key for, who has the public key (does the public key even matter)? I currently do not understand what is being done with this key, therefore I am wondering why one would just need the private part :)

The RSA key is for signing the JWT's generated for OIDC so that RP's know the JWT's are valid. They are a requirement for OpenID Connect base support. Ideally long term we will be aiming to add this as a web config item; adding, generating, and rotating RSA keys.

Regarding GitLab, sadly this will require the userinfo endpoint which we missed in our initial implementation. I have a few things I want to get done for the next release, and I will see if we can squeeze that one in.

**Comment by james-d-elliott** [comment]
> I am wondering why one would just need the private part :)

I forgot to answer this! The thing with RSA private keys in PEM format is that you can derive the public key from the private key easily. You can do this with openssl with the following syntax:

`openssl rsa -in rsa.key -pubout > rsa.pem`

**Comment by georglauterbach** [comment]
@james-d-elliott Thank you very much!

All questions are now answered. Can't wait to see the userinfo endpoint added :)

**Comment by georglauterbach** [comment]
Chiming in again to provide a bit of feedback - call it an error report during beta:

I was setting up [MinIO](https://min.io/) in a K3s Kubernetes cluster with Authelia and tried to make Authelia the OIDC provider for MinIO (roughly following [this documentation](https://github.com/minio/minio/blob/master/docs/sts/web-identity.md)).

The Authelia OIDC configuration looks like this:

``` YAML
identity_providers:
  oidc:
    - id: minio
      description: MinIO
      secret: somesecretsecret
      authorization_policy: one_factor
      redirect_uris:
        - https://redirect.example.com/minio/login/openid
      scopes:
        - openid
        - email
        - profile
      response_types:
        - id_token
```

Just for the sake of completeness, here is a part of the MinIO environment variable configuration

``` YAML
MINIO_ROOT_USER: myrootusername
MINIO_IDENTITY_OPENID_SCOPES:     openid,profile,email
MINIO_IDENTITY_OPENID_CLIENT_ID:  minio
MINIO_IDENTITY_OPENID_CONFIG_URL: https://authelias-subdomain.example.com/.well-known/openid-configuration
```

and of course the secret "somesecretsecret" in form of a Kubernetes secret.

---

To the error at hand: The Authelia logs show (lightly formatted)

``` TXT
level=error
msg  ="Error occurred in NewAuthorizeRequest: invalid_state"
stack="
  github.com/authelia/authelia/internal/handlers/handler_oidc_authorize.go:19
  oidcAuthorize\ngithub.com/authelia/authelia/internal/middlewares/http_to_authelia_handler_adaptor.go:113 
  NewHTTPToAutheliaHandlerAdaptor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:50 
  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.12/router.go:414
  (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14 
  LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.24.0/server.go:2219
  (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:223
  (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:195 
  (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371
  goexit
"
```

and MinIO shows this badge:

![Screenshot 2021-07-01 at 11-05-28 MinIO Browser](https://user-images.githubusercontent.com/44545919/124098003-6c139080-da5c-11eb-8318-a98c3f417ba5.png)

---

Is there something I am missing here?

---

PS: I also say some new images on DockerHub about the userinfo endpoint. Ping me if I can / shall test an image.

**Comment by james-d-elliott** [comment]
> 
> 
> Chiming in again to provide a bit of feedback - call it an error report during beta:
> 
> I was setting up [MinIO](https://min.io/) in a K3s Kubernetes cluster with Authelia and tried to make Authelia the OIDC provider for MinIO (roughly following [this documentation](https://github.com/minio/minio/blob/master/docs/sts/web-identity.md)).
> 
> The Authelia OIDC configuration looks like this:
> 
> ```yaml
> identity_providers:
>   oidc:
>     - id: minio
>       description: MinIO
>       secret: somesecretsecret
>       authorization_policy: one_factor
>       redirect_uris:
>         - https://redirect.example.com/minio/login/openid
>       scopes:
>         - openid
>         - email
>         - profile
>       response_types:
>         - id_token
> ```
> 
> Just for the sake of completeness, here is a part of the MinIO environment variable configuration
> 
> ```yaml
> MINIO_ROOT_USER: myrootusername
> MINIO_IDENTITY_OPENID_SCOPES:     openid,profile,email
> MINIO_IDENTITY_OPENID_CLIENT_ID:  minio
> MINIO_IDENTITY_OPENID_CONFIG_URL: https://authelias-subdomain.example.com/.well-known/openid-configuration
> ```
> 
> and of course the secret "somesecretsecret" in form of a Kubernetes secret.
> 
> To the error at hand: The Authelia logs show (lightly formatted)
> 
> ```
> level=error
> msg  ="Error occurred in NewAuthorizeRequest: invalid_state"
> stack="
>   github.com/authelia/authelia/internal/handlers/handler_oidc_authorize.go:19
>   oidcAuthorize\ngithub.com/authelia/authelia/internal/middlewares/http_to_authelia_handler_adaptor.go:113 
>   NewHTTPToAutheliaHandlerAdaptor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:50 
>   AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.12/router.go:414
>   (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14 
>   LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.24.0/server.go:2219
>   (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:223
>   (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:195 
>   (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371
>   goexit
> "
> ```
> 
> and MinIO shows this badge:
> 
> ![Screenshot 2021-07-01 at 11-05-28 MinIO Browser](https://user-images.githubusercontent.com/44545919/124098003-6c139080-da5c-11eb-8318-a98c3f417ba5.png)
> 
> Is there something I am missing here?
> 
> PS: I also say some new images on DockerHub about the userinfo endpoint. Ping me if I can / shall test an image.

Strange, I believe this is because MinIO is sending a short state value, let me make a quick modification to see if we can get some more information here.

**Comment by james-d-elliott** [comment]
@georglauterbach I figured out why. We have configured a minimum length of 8 for state and MinIO isn't providing it. I've pushed a branch that lets you configure it (docker tag test-oidc-entropy).

https://buildkite.com/authelia/authelia/builds/6132

I would attempt to use a value of 6, the default is 8. You can configure it like this:

```yaml
identity_providers:
  oidc:
    minimum_parameter_entropy: 6
```

**Comment by georglauterbach** [comment]
> ```yaml
> minimum_parameter_entropy: 6
> ```

I will test this immediately and provide you with the results here.

**Comment by james-d-elliott** [comment]
> 
> 
> > ```yaml
> > minimum_parameter_entropy: 6
> > ```
> 
> I will test this immediately and provide you with the results here.

Sounds good to me. If 6 doesn't work, just decrease it until  it works. Keep in mind if you can force MinIO to increase the length of the state value that is highly preferable for entropy which affects security.

**Comment by georglauterbach** [comment]
@james-d-elliott Still the same, here is the log with debug loglevel: <https://wtools.io/paste-code/b5EF>

**Comment by james-d-elliott** [comment]
> If this is the case, I will not bother with this here anymore :)

Not a bother to get support here! Though decreasing it to zero should work. I will take a look tomorrow at the library we're using to figure out why.

**Comment by james-d-elliott** [comment]
@georglauterbach it's because the library we're using assumes 0 means set the default of 8 (error message should confirm this). Try setting it to `-1`. :)

**Comment by georglauterbach** [comment]
> this

Sadly, -1 does not seem to work.

**Comment by james-d-elliott** [comment]
I'll take a closer look tomorrow, I made a comment on the other issue.

**Comment by georglauterbach** [comment]
> I'll take a closer look tomorrow, I made a comment on the other issue.

Thank you very much!

**Comment by bozerkins** [comment]
`In the Authelia configuration, identity_providers::oidc::clients::secret is stored in plain text. Will this change?`

I would like to contribute my time to see this change in nearest future. Is there any design / vision for the implementation?

**Comment by clems4ever** [comment]
I think https://github.com/authelia/authelia/pull/2053 will help us solve the initial issue with those secrets. Am I right, @james-d-elliott?

**Comment by davama** [comment]
@clems4ever 
@james-d-elliott 

possible to have the secret `cleartext/hashed` as an option?

**Comment by james-d-elliott** [comment]
> I think #2053 will help us solve the initial issue with those secrets. Am I right, @james-d-elliott?

I don't think it will, configuring slices of structs is not something either viper or koanf does OOB.

> I would like to contribute my time to see this change in nearest future. Is there any design / vision for the implementation?

This is definitely on the cards. The idea for doing it in plain text was to make implementation easier, make it easy for people to setup, and to make a clear design decision about how to adjust existing libraries.

In particular I think it would be benevolent to redo the file auth provider so the hash functions are reusable.

> possible to have the secret `cleartext/hashed` as an option?

Usually I would say we'd force a hash on people; however as this is a shared secret (meaning it has to be plaintext or in a feel-good decryptable format on the other end) I think it's probably completely fine to give users an option.

**Comment by bozerkins** [comment]
My current setup of Authelia is in the k8s cluster via helm chart. I was thinking of introducing support for oidc secrets taken from env variables (via some mapping to oidc client ID) and them making changes to the helm chart to support this. We're using kubeseal for storing secrets in the cluster so the approach looks to be secure enough.

I was reading the docs and saw that storing secrets in the ENV variables is not advices, so may be there'd be some other way to dealing with this? Having a separate file for client secrets may be?

**Comment by james-d-elliott** [comment]
@bozerkins so currently because of the clients (and ACL rules) being in a slice of structs it is rather difficult to make this happen. However it is 100% something in my mind to get working.

With the Koanf PR we would however be able to split the configuration into multiple files... this has not been tested with a list of structs but I imagine it works (I can test it). Theoretically if that works you'd be able to make your secrets a client file with contents like so:

```yaml

identity_providers:
  oidc:
    clients:
      - ....
```

**Comment by bozerkins** [comment]
Thank you for the response! I got the general idea of how it might work. I will try to test it too with the Koanf PR. Ping me on Discord if you'd like any help with that :)

**Comment by georglauterbach** [comment]
I can confirm that GitLab works! Do I always have to click the consent button? The log reads:

``` INI
level=debug msg="User georg must consent with scopes openid, groups, email, profile" method=GET path=/api/oidc/authorize remote_ip=xxx.xxx.xxx.xxx
```

**Comment by james-d-elliott** [comment]
> Thank you for the response! I got the general idea of how it might work. I will try to test it too with the Koanf PR. Ping me on Discord if you'd like any help with the feature

Feel free to do the same! Thanks for being involved.




> 
> 
> I can confirm that GitLab works! Do I always have to click the consent button? The log reads:
> 
> ```ini
> level=debug msg="User georg must consent with scopes openid, groups, email, profile" method=GET path=/api/oidc/authorize remote_ip=xxx.xxx.xxx.xxx
> ```

At the present time that is the case. Currently we don't store anything about OIDC in SQL, it's all in memory. I'm not entirely sure what other providers do for this or what makes sense to do. The SQL storage portion will be in phase 3, we're about to release phase 2 which includes userinfo in 4.30, phase 3 will probably be 4.31 or 4.32.

**Comment by georglauterbach** [comment]
> At the present time that is the case. Currently we don't store anything about OIDC in SQL, it's all in memory. I'm not entirely sure what other providers do for this or what makes sense to do. The SQL storage portion will be in phase 3, we're about to release phase 2 which includes userinfo in 4.30, phase 3 will probably be 4.31 or 4.32.

Alright, no big deal, just wanted to know whether I may had misconfigured something. I will also test MinIO ASAP again.

**Comment by lukas-hetzenecker** [comment]
Can confirm Gitlab works perfectly with v4.30.1, thank you! :partying_face:

**Comment by james-d-elliott** [comment]
> 
> 
> Can confirm Gitlab works perfectly with v4.30.1, thank you! 🥳

No worries. Glad it works for you (though I did test it!!).

**Comment by lhaus** [comment]
Also working perfectly with Gitea v1.14.5

**Comment by james-d-elliott** [comment]
> 
> 
> Also working perfectly with Gitea v1.14.5

Awesome!!

**Comment by adyanth** [comment]
@lhaus would you be so kind to provide the configs for OIDC? I currently use Gitea with LDAP and was looking to move to Authelia with Traefik.

**Comment by georglauterbach** [comment]
If this is not to much too ask, you guys could add this information and the callback URIs to the documentation under community. I already create the document :)

**Comment by lhaus** [comment]
@adyanth 
![image](https://user-images.githubusercontent.com/18512463/128477591-3f19b371-7d02-4830-9c15-8c19caeed914.png)

For client id and secret use the respective vars from the config
Redirect URI is `https://gitea.yourdomain.com/user/oauth2/Authelia/callback`, with `Authelia` being the text in the "Authentication Name" field

**Comment by james-d-elliott** [comment]
> 
> 
> Is there an easy way to debug the response Authelia is generating? Even with log level trace, I don't see the response.
> 
> The issue I have is that GitLab isn't using `sAMAccountName` as uid, but I don't know what's the appropriate setting for [`uid_field`](https://docs.gitlab.com/ee/administration/auth/oidc.html#example-configurations).

GitLab's OmniAuth default is sub, which we set to the username used to login to Authelia. There is no  way specific in Authelia to debug responses, this is in my experience usually done at the OIDC RP.

**Comment by oredin** [comment]
Hi !

Thanks for the nice work. I'm using Authelia OIDC with Gitlab, PowerDNSAdmin and Portainer successfully for some times now.

I have just a little problem with Portainer when my portainer session expires while i'm still authenticated with Authelia. It seems Portainer need the user to reauthenticate.

An improvment to keep in mind for the next releases !

**Comment by james-d-elliott** [comment]
@oredin are there any logs in portainer or Authelia indicating an issue when trying to renew the token? We have the refresh token  lifespan set to an adequate time for them to  be able to refresh it by default so I'm inclined to say that is something out of our control. 

Here are the  docs regarding lifespans: https://www.authelia.com/docs/configuration/identity-providers/oidc.html#access_token_lifespan

You can technically up those lifespans however it is not how OIDC is meant to operate. Also until we implement front-channel/back-channel logouts it's very insecure to increase these too much. 

OIDC/SAML/etc authorize a person until the lifespan unless manual intervention happens. Just because the session by which you authorized the OIDC session logs out does not mean all OIDC sessions are terminated. In the  event a logout occurs, the short lifespan is meant to ensure the OIDC session ends shortly after since a refresh operation should fail.

**Comment by oredin** [comment]
@james-d-elliott I got the traces below in Authelia and the only thing I have in Portainer is the error message in the URL which is `The Authorization Server requires End-User authentication. Failed to validate OpenID Connect request because prompt was set to 'login' but auth_time ('2021-11-11 11:02:45  0100 CET') happened before the authorization request ('2021-11-11 11:03:07  0100 CET') was registered, indicating that the user was not re-authenticated which is forbidden.`

I don't think it's due to the token lifespan. Portainer seems to need a full reauthentication by Authelia to accept the user. If i log out from Authelia and try again to log in Portainer, everything is fine.

> Error occurred in NewAuthorizeResponse: login_required
> github.com/ory/x/errorsx.WithStack
> github.com/ory/x@v0.0.288/errorsx/errors.go:38
> github.com/ory/fosite/handler/openid.(*OpenIDConnectRequestValidator).ValidatePrompt
> github.com/ory/fosite@v0.40.2/handler/openid/validator.go:150
> github.com/ory/fosite/handler/openid.(*OpenIDConnectExplicitHandler).HandleAuthorizeEndpointRequest
> github.com/ory/fosite@v0.40.2/handler/openid/flow_explicit_auth.go:61
> github.com/ory/fosite.(*Fosite).NewAuthorizeResponse
> github.com/ory/fosite@v0.40.2/authorize_response_writer.go:43
> github.com/authelia/authelia/v4/internal/handlers.oidcAuthorization
> github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:81
> github.com/authelia/authelia/v4/internal/middlewares.NewHTTPToAutheliaHandlerAdaptor.func1
> github.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113
> github.com/authelia/authelia/v4/internal/middlewares.AutheliaMiddleware.func1.1
> github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51
> github.com/fasthttp/router.(*Router).Handler
> github.com/fasthttp/router@v1.4.3/router.go:414
> github.com/authelia/authelia/v4/internal/middlewares.LogRequestMiddleware.func1
> github.com/authelia/authelia/v4/internal/middlewares/log_request.go:14
> github.com/valyala/fasthttp.(*Server).serveConn
> github.com/valyala/fasthttp@v1.30.0/server.go:2266
> github.com/valyala/fasthttp.(*workerPool).workerFunc
> github.com/valyala/fasthttp@v1.30.0/workerpool.go:223
> github.com/valyala/fasthttp.(*workerPool).getCh.func1
> github.com/valyala/fasthttp@v1.30.0/workerpool.go:195
> runtime.goexit
> runtime/asm_amd64.s:1581" method=GET path=/api/oidc/authorize remote_ip=XX.XX.XX.XX stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:101          oidcAuthorization
> github.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113 NewHTTPToAutheliaHandlerAdaptor.func1
> github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51                  AutheliaMiddleware.func1.1
> github.com/fasthttp/router@v1.4.3/router.go:414                                              (*Router).Handler
> github.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       LogRequestMiddleware.func1
> github.com/valyala/fasthttp@v1.30.0/server.go:2266                                           (*Server).serveConn
> github.com/valyala/fasthttp@v1.30.0/workerpool.go:223                                        (*workerPool).workerFunc
> github.com/valyala/fasthttp@v1.30.0/workerpool.go:195                                        (*workerPool).getCh.func1
> runtime/asm_amd64.s:1581                                                                     goexit
>

**Comment by james-d-elliott** [comment]
I can see why this is the case, I can fix this relatively easily. Thanks for the helpful logs.

**Comment by oeiber** [comment]
Is it possible to define rules for oidc clients? for example:
- single factor for specific subnets, elswhere two factor
- restrict access to oicd clients to specific user groups

thank you!

**Comment by james-d-elliott** [comment]
> 
> 
> Is it possible to define rules for oidc clients? for example:
> 
>     * single factor for specific subnets, elswhere two factor
> 
>     * restrict access to oicd clients to specific user groups
> 
> 
> thank you!

Currently this is not possible. It will be something we have to add in the future. I have some ideas on how this would be done, but just trying to figure out the most intuitive and useful way to do it.

**Comment by james-d-elliott** [comment]
> 
> 
> I can see why this is the case, I can fix this relatively easily. Thanks for the helpful logs.

I thought this would be easy @oredin but on second look it may not be. I'll do what I can however it looks like a potentially complex flow we need to implement, may take some time.

**Comment by oredin** [comment]
> > I can see why this is the case, I can fix this relatively easily. Thanks for the helpful logs.
> 
> I thought this would be easy @oredin but on second look it may not be. I'll do what I can however it looks like a potentially complex flow we need to implement, may take some time.

No problem. After some tweaking, I found that if you enable the SSO option in Portainer, it doesn't ask for a reauthentication.

Cheers !

**Comment by Scharunge** [comment]
Hey everyone,

Maybe someone knows whats wrong with my oidc. I have setup the oidc provider like described in the docs. Then I tried to setup everything in GiTea like @zotanmew  described. 

I alway get an internal server error and the GiTea container logs are telling me  

```
Failed to create OpenID Connect Provider with name [my app nane] with url 'https://[mydomain]/.well-known/openid-configuration' Get "https://[mydomain]/.well-known/openid-configuration": dial tcp [my public ip]:443: i/o timeout"
```
I also tried to implement it with portainer-ce. I was able to get the Permissions Request from authellia. But as portainer was trying to login it failed.

The message from the portainer log was mostly the same as from GiTea.

`Failed retrieving access token: Post \"https://[mydomain]/api/oidc/token\": dial tcp [pubic ip]:443: i/o timeout"`

I'm using traefik 2.5.4 as reverse proxy. I assume  something is misconfigured. Since no one else seems to have issues like this. I just find it stange that in case of porttainer the requests seem to work until it wants to recieve the token.

Maybe someone already got a soulution for my problem. Of course I can provide more information about my configuration, if someone is willing to help me.

**Comment by james-d-elliott** [comment]
Can you confirm the openid-configuration URL is correct by visiting it? @Scharunge

**Comment by Scharunge** [comment]
> Can you confirm the openid-configuration URL is correct by visiting it? @Scharunge

Thus ist the Response I geht
{"issuer":"https://myurl","jwks_uri":"https://myurl/api/oidc/jwks","authorization_endpoint":"https://myurl/api/oidc/authorize","token_endpoint":"https://myurl/api/oidc/token","revocation_endpoint":"https://myurl/api/oidc/revoke","userinfo_endpoint":"https://myurl/api/oidc/userinfo","id_token_signing_alg_values_supported":["RS256"],"userinfo_signing_alg_values_supported":["none","RS256"],"subject_types_supported":["public"],"response_types_supported":["code","token","id_token","code token","code id_token","token id_token","code token id_token","none"],"response_modes_supported":["form_post","query","fragment"],"scopes_supported":["openid","offline_access","profile","groups","email"],"claims_supported":["aud","exp","iat","iss","jti","rat","sub","auth_time","nonce","email","email_verified","alt_emails","groups","name"],"request_uri_parameter_supported":false,"backchannel_logout_supported":false,"frontchannel_logout_supported":false,"backchannel_logout_session_supported":false,"frontchannel_logout_session_supported":false}

**Comment by james-d-elliott** [comment]
How interesting. I'm assuming you replaced your domain with https://myurl?

**Comment by Scharunge** [comment]
Yes

**Comment by Scharunge** [comment]
> How interesting. I'm assuming you replaced your domain with https://myurl? Edit: Just read the last part. If the URL in the error log shows that, you'd expect that it's working, unless there is an issue with it's path to your server. Can you perform a curl from that container to the same URL?

I will try that

**Comment by Scharunge** [comment]
@james-d-elliott I performend a curl to https://myurl/.well-known/openid-configuration and got a Operation timed out.

I tried to find something on Google but the only thing I found was that docker containers  are not able to make requests to another container via public url when they are running on the same host.

**Comment by cazzoo** [comment]
Hi there! I almost finished integration of Authelia with grafana but I have some troubles to map role to authenticated user.
Indeed, I see no way to add role to the generated token...
Here is a sample of the generated token with the following scope:
`{
  "at_hash": "K8hPlkUPG9U11Uy7KeVfWw",
  "aud": [
    "grafana"
  ],
  "auth_time": 1639436914,
  "email": "useremail@mydomain.com",
  "email_verified": true,
  "exp": 1639440531,
  "groups": [
    "admins",
    "dev"
  ],
  "iat": 1639436931,
  "iss": "https://auth.mydomain.com",
  "jti": "c04676c3-88a8-48df-9e57-ddca303e659e",
  "name": "Caz",
  "rat": 1639436908,
  "sub": "caz"
}`
And here is the my user database file (yaml):
`users:
  caz:
    displayname: "Caz"
    password: "...ENC..."
    email: useremail@mydomain.com
    groups:
      - admins
      - dev
    role: "Admin"`

**Comment by james-d-elliott** [comment]
You need to set your role_attribute_path.

```
role_attribute_path = contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || 'Viewer'
```

**Comment by cazzoo** [comment]
> You need to set your role_attribute_path.
> 
> ```
> role_attribute_path = contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || 'Viewer'
> ```

Thank you! This is a good workaround of the ACL.
Just for my information, how should this be handled in the future? Should it be managed using custom scopes?

**Comment by RefineryX** [comment]
> @james-d-elliott I performend a curl to https://myurl/.well-known/openid-configuration and got a Operation timed out.
> 
> I tried to find something on Google but the only thing I found was that docker containers are not able to make requests to another container via public url when they are running on the same host.
> 
> I also tried the internal docker network http://authelia:9091/.well-known/openid-configuration. But then I get Error 400

I'm facing this exact issue... did you find a way @Scharunge ? 

I have an internal only domain (my_domain.com) which I have rewritten on my DNS server to resolve to my server. I can access everything from each client auth.my_domain.com etc but I am unable to resolve this inside a container... such as Portainer.

**Comment by Scharunge** [comment]
@RefineryX  no I haven't found a solution yet.

**Comment by james-d-elliott** [comment]
I'm not sure if I suggested it earlier, but if you add a DNS alias to your *proxy* container it may resolve this issue.

**Comment by revilo951** [comment]
> I have an internal only domain (my_domain.com) which I have rewritten on my DNS server to resolve to my server. I can access everything from each client auth.my_domain.com etc but I am unable to resolve this inside a container... such as Portainer.

Have you tried adding your local DNS to the container? `--dns x.x.x.x`

**Comment by james-d-elliott** [comment]
Adding it to the Authelia container wouldn't work just FYI, it would have to be the proxy container.

**Comment by priceaj** [comment]
The closure comment of #1008 Mentions that the change under this issue will allow users to authenticate with their plex account. 

I'm not very familiar with OpenID Connect, but as far as I can tell the change under this issue does not implement this. It seems to turn Authelia into an OpenID Identity Provider rather than a client of another provider. 

This is alluded to in the [documentation](https://www.authelia.com/docs/configuration/identity-providers/oidc.html) which says: 

```The Relying Party role is the role which allows an application to use GitHub, Google, or other OpenID Connect providers for authentication and authorization. We do not intend to support this functionality at this moment in time.```

Even if this "Relaying Party" role was implemented, would Plex still have to return a valid JWT with the OpenID Connect fields in order to be supported?

Is my understanding correct or is it possible to use this change to authenticate with a third party which supports OAUTH 2.0?

If not, should #1008 be reopened/another enhancement request be logged?

I note that https://github.com/authelia/authelia/issues/189#issuecomment-419462184 mentioned this change to have Authelia act as a replacement for [oauth2-proxy/oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) which also seems to act as a client, so I'd imagine that they were hoping for something similar.

**Comment by elcomtik** [comment]
@james-d-elliott is there any development on stage beta3 mentioned in [docs](https://github.com/authelia/authelia/blob/master/docs/configuration/identity-providers/oidc.md)?

**Comment by ridvanaltun** [comment]
I integrated Authelia with Guacamole, I can create document under `docs/community/oidc-integrations` to show how to do it.

**Comment by ridvanaltun** [comment]
> it's because the library we're using assumes 0 means set the default of 8 (error message should confirm this). Try setting it to `-1`. :)

Can you document it? https://www.authelia.com/docs/configuration/identity-providers/oidc.html#minimum_parameter_entropy

**Comment by james-d-elliott** [comment]
> @james-d-elliott is there any development on stage beta3 mentioned in [docs](https://github.com/authelia/authelia/blob/master/docs/configuration/identity-providers/oidc.md)?

Hey we're working on this next, I've done investigation into what the underlying library requires us to store. We have to get Webauthn sorted first, then it should be the thing I work on.

> Can you document it? https://www.authelia.com/docs/configuration/identity-providers/oidc.html#minimum_parameter_entropy

If this works then yes.

**Comment by ridvanaltun** [comment]
> > @james-d-elliott is there any development on stage beta3 mentioned in [docs](https://github.com/authelia/authelia/blob/master/docs/configuration/identity-providers/oidc.md)?
> 
> Hey we're working on this next, I've done investigation into what the underlying library requires us to store. We have to get Webauthn sorted first, then it should be the thing I work on.
> 
> > Can you document it? https://www.authelia.com/docs/configuration/identity-providers/oidc.html#minimum_parameter_entropy
> 
> If this works then yes.

Yes it works

**Comment by bkupidura** [comment]
Hey, is there any plan to add `Authorization: Bearer <token>` with work around oidc? 
It will allow other apps to authorize users based on JWT token.

Currently im using Authelia+OAuth2-Proxy to pass Authorization header to backend (it works e.g with kubernetes-dashboard or node-red). But with OAuth2-proxy i lose awsome part of Authelia - Access Control.

If interested i can share my setup details how to authorize against kubernetes-dashboard to show use-case for Bearer token.

**Comment by james-d-elliott** [comment]
> 

We can definitely investigate it. Can you share your details like suggested? It will likely depend on if this solution supported by the dashboard/k8s itself like the apiserver OIDC config. Also lets make this a separate FR.

**Comment by bkupidura** [comment]
@james-d-elliott really appreciate interest in that.

I created https://github.com/authelia/authelia/issues/2922 so we can move discussion there, if any further clarification or details are needed just ping me.

PS. Authelia is awsome!

**Comment by james-d-elliott** [comment]
> Suggesting that this be added to the misc "may be implemented" features in the [roadmap](https://www.authelia.com/docs/roadmap/oidc.html) if there is interest from developers.

It's definitely something I've been looking at as I understand the spec more. I am happy to add it to that section, I have a feeling it wont be part of the GA release, but will be added later. I also think moving clients from the configuration file to SQL is a must for this feature which means implementing the admin interface, as otherwise the clients will be split between two locations.

Also as far as I understand dynamic registration the main use case is mobile apps, as it allows developers to utilize OpenID Connect and get a unique client id and client secret (basically a unique client) per application. Usually this is also only used when there is a static discovery URL, which means the main benefit for using it is when a company is developing internal applications. For these reasons I felt the use case was rather limited when it comes to Authelia, and figure it's probably something that will be desired in the future by a company which has an internal development department rather than the majority of users, if that makes sense.

That being said I'd be interested in the following:

- If you or a business you work for would benefit from this.
- If you know of any open source projects that implement the OIDC RP with OIDC DR support with a custom issuer URL (my guess is none but I may be mistaken).
- If you know of any open source libraries that implement OIDC RP with OIDC DR support out of the box.

**Comment by adyanth** [comment]
For point 2, does this look like what you wanted? 
https://github.com/keycloak/keycloak-documentation/blob/main/securing_apps/topics/client-registration.adoc

**Comment by james-d-elliott** [comment]
That is the OP side, RP refers to the "client" implementation, i.e. the projects they refer to. No stress if you don't know of any, however if you did it'd be cool to know about them is all. I'm curious how clients actually implement this mostly, to see how popular it is outside of mobile app development.

**Comment by adyanth** [comment]
As per this: https://openid.net/developers/certified/

The node-openid-client, phpOIDC, and all of the python implementations support Dynamic RP. Looks like the Gluu oxd client supports it too.

**Comment by james-d-elliott** [comment]
Oh nice, didn't know they listed that in that resources section! Thanks a lot.

**Comment by michaelkrieger** [comment]
> I am happy to add it to that section, I have a feeling it wont be part of the GA release, but will be added later.

Yes, more thinking it will evolve to the point where this will be the norm eventually as more apps rely on OpenID Connect.

I certainly don't think it should be a priority or even have anything more than a "maybe one day" on the roadmap.

The suggestion came from starting to set up an app with Authelia and my first thought being "why can't I just point the app to the authelia endpoint and let it generate and negotiate these secrets/keys", and a brief search found registration in the spec.

> I also think moving clients from the configuration file to SQL is a must

For most authelia implementations, SQLite is very likely the way, caching a small number of clients entirely in memory.
I hesitate to add external dependencies of PostgreSQL/MySQL *as anything more than optional* for such a critical access mechanism.

> Also as far as I understand dynamic registration the main use case is mobile apps

Dynamic Registration allows anyone to create applications without a token.  Simply passing the client name, and callback/redirect URLs and you can register an app. [Auth0 has an implementation](https://auth0.com/docs/get-started/applications/dynamic-client-registration).

Long term, as more applications adopt OpenID Connect RP roles in their projects (which is still relatively recent), it could mean configuring an application entirely in the admin side of a client program without messing with the Authelia configuration at all. I believe this is a "if you build it, they may come" type of scenario, as there frankly aren't many easy to use implementations. Take any self-hosted style application that allows external authentication or basic-auth style authentication. 

This could also be something implemented *eventually* by reverse proxies like Traefik in their [OIDC configuration](https://doc.traefik.io/traefik-enterprise/middlewares/oidc/) where individual services could auto-register.

**Comment by james-d-elliott** [comment]
My main point regarding DR's use case being for mobile apps is that the user doesn't need to know anything about the OP in order to authenticate with it, but each client obtains its own client settings etc.  so authors do not need to hard code a client_id and client_secret into their app.

In Authelia's case all that they'd need to provide is their Authelia URL technically since discovery should cover everything else.

> I hesitate to add external dependencies of PostgreSQL/MySQL _as anything more than optional_ for such a critical access mechanism.

We already support SQLite and it's required you pick a SQL type as part of configuration. So I'm not sure I understand. Though PostgreSQL is easily the _best_ solution it's not required.

**Comment by michaelkrieger** [comment]
> We already support SQLite and it's required you pick a SQL type as part of configuration.
> So I'm not sure I understand. Though PostgreSQL is easily the _best_ solution it's not required.
Agreed.  This comment needs no action.

**Comment by Scharunge** [comment]
> > @james-d-elliott I performend a curl to https://myurl/.well-known/openid-configuration and got a Operation timed out.
> > I tried to find something on Google but the only thing I found was that docker containers are not able to make requests to another container via public url when they are running on the same host.
> > I also tried the internal docker network http://authelia:9091/.well-known/openid-configuration. But then I get Error 400
> 
> I'm facing this exact issue... did you find a way @Scharunge ?
> 
> I have an internal only domain (my_domain.com) which I have rewritten on my DNS server to resolve to my server. I can access everything from each client auth.my_domain.com etc but I am unable to resolve this inside a container... such as Portainer.

After month of not thinking about it. Today I just tried to configure OpenId Connect in portainer and gittea again. To my surprise it worked even though I changed nothing on my proxy config.

**Comment by Kramins** [comment]
I was playing around with the OpenID as well, got it working and for an unknown reason I started getting.

`failed to parse PEM block containing the key`

I was/am using the helm chart v0.8.34, I tried adding the secret OIDC_PRIVATE_KEY and leaving it blank to allow for auto generation, both resulting in the same error.

**Comment by helmut72** [comment]
> I integrated Authelia with Guacamole, I can create document under `docs/community/oidc-integrations` to show how to do it.

Do you have published both configs somewhere?

**Comment by yscialom** [comment]
Hello, for what it's worth, I'm been using OpenID with authelia+nextcloud for six months, works like a charm.

* Authelia's config: [`configuration.yml:oidc`](https://github.com/yscialom/pinanas/blob/develop/src/templates/authelia/config/configuration.yml.j2#L129)
* Nextcloud installation: [`occ user_oidc:provider`](https://github.com/yscialom/pinanas/blob/develop/src/templates/nextcloud/build/config/custom-cont-init.d/20-install-user_oidc.sh.j2#L29)

I'm using the docker image `authelia/authelia:4.35`. Hope it helps.

**Comment by helmut72** [comment]
Thanks, but asked especially for Guacamole, where groups are important. To give users permission to specific RDP connections without creating the same RDP connection many times

**Comment by james-d-elliott** [comment]
New OpenID Connect features are being completed as per the [blog post](https://www.authelia.com/blog/4.37-pre-release-notes/).

Also see the [OpenID Connect Roadmap (beta 5)](https://www.authelia.com/roadmap/active/openid-connect/#beta-5) for OpenID Connect specific features in this release.

**Comment by AndreKR** [comment]
Is this about *being* an OIDC identity provider or about *using* an external OIDC identity provider as user database?

**Comment by james-d-elliott** [comment]
Provider.

**Comment by james-d-elliott** [comment]
Check the Client RBAC section, while not clearly stated right now (will update shortly), it's actually coming in 4.38.

**Comment by james-d-elliott** [comment]
All the information is already available: https://github.com/authelia/authelia/discussions/categories/pre-release-feedback

**Comment by mikew** [comment]
> Thanks, but asked especially for Guacamole, where groups are important. To give users permission to specific RDP connections without creating the same RDP connection many times

FYI, support for this has been in Guacamole for years, it's just never made it to the Docker container :(. What I've done for now is overwrite the `start.sh` with [their `start.sh` from master](https://github.com/apache/guacamole-client/blob/master/guacamole-docker/bin/start.sh) and set `OPENID_GROUPS_CLAIM_TYPE=groups`.

Support for this environment variable might finally land in 1.5.5 or 1.60, 🤷

**Comment by james-d-elliott** [comment]
Thanks for everyone who participated constructively in this major undertaking. We are [OpenID Certified™](https://github.com/authelia/authelia/discussions/9525) as of v4.39. 

We have some additional large changes in the upcoming versions which will probably be breaking at least in-part but we will soon stabilize this major feature and close this issue off at the time which it's graduated from a beta into a GA feature, in favor of sub-issues which I've recently linked.

**Comment by hikarukin** [comment]
@james-d-elliott Sounds (based on the certification, congrats by the way) that this issue can now be closed?

(just stumbled across this issue while researching something)

**Comment by Crowley723** [comment]
> [@james-d-elliott](https://github.com/james-d-elliott) Sounds (based on the certification, congrats by the way) that this issue can now be closed?
> 
> (just stumbled across this issue while researching something)

We still have a number of OIDC features/specs that need to be implemented before we consider OIDC 1.0 complete. (See the [support chart](https://www.authelia.com/integration/openid-connect/introduction/#support-chart)). Additionally there are a couple sub-issues for this issue.

**Comment by james-d-elliott** [comment]
Also see the comment above yours.

**Comment by hikarukin** [comment]
Apologies, I guess I misread that. 👍
